services:
  ai-validation-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: viera-ai-validation
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - temp_files:/tmp/viera_validation
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  temp_files: